"""
Align a module's third-party PackageReference versions to the platform's.

The authoritative versions come from bundles/v{N}/platform_package_reference.md (generated by
platform_package_reference.py from vc-platform's solution, i.e. the shipped project set). Only packages that the
platform pins at a SINGLE, plain version are aligned; conflicts and ranges are left for a manual decision.

Byte-level edits: line endings and formatting are preserved. Idempotent.

Usage: python align_3rdparty.py <repo_dir> [--apply]
"""
import argparse
import glob
import os
import re

import config

REFERENCE_MD = config.out("platform_package_reference.md")
PACKAGE_REF = re.compile(rb'(<PackageReference\s+Include=")([^"]+)("\s+Version=")([^"]+)(")')
SKIP = re.compile(r'[\\/](bin|obj|node_modules)[\\/]')


def platform_versions(reference_md=REFERENCE_MD):
    """package id -> version, from the 'All packages' table (single clean versions only)."""
    result = {}
    in_table = False
    for line in open(reference_md, encoding="utf-8"):
        if line.startswith("## All packages"):
            in_table = True
            continue
        if in_table and line.startswith("## "):
            break
        if not (in_table and line.startswith("|")):
            continue
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cells) < 2 or cells[0] in ("Package", "---"):
            continue
        versions = re.findall(r"`([^`]+)`", cells[1])
        if len(versions) == 1 and not any(ch in versions[0] for ch in "[](),"):
            result[cells[0]] = versions[0]
    return result


def align(repo_dir, apply=False):
    """Return [(file, package, old, new)]; rewrite the files when apply=True."""
    targets = platform_versions()
    changes = []
    for path in glob.glob(os.path.join(repo_dir, "**", "*.csproj"), recursive=True):
        if SKIP.search(path):
            continue
        data = open(path, "rb").read()

        def repl(m):
            package, current = m.group(2).decode(), m.group(4).decode()
            target = targets.get(package)
            if package.startswith("VirtoCommerce.") or not target or current == target:
                return m.group(0)
            changes.append((os.path.relpath(path, repo_dir), package, current, target))
            return m.group(1) + m.group(2) + m.group(3) + target.encode() + m.group(5)

        new = PACKAGE_REF.sub(repl, data)
        if apply and new != data:
            open(path, "wb").write(new)
    return changes


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("repo_dir")
    ap.add_argument("--apply", action="store_true")
    args = ap.parse_args()
    changes = align(args.repo_dir, args.apply)
    for path, package, old, new in changes:
        print(f"  {package}: {old} -> {new}   [{path}]")
    print(f"{'APPLIED' if args.apply else 'WOULD CHANGE'}: {len(changes)} ref(s) in {os.path.basename(os.path.abspath(args.repo_dir))}")


if __name__ == "__main__":
    main()
