"""
Compute the dependency-ordered update waves for a stable-release bundle.

Read-only. Reads a bundle package.json + modules_v3.json, picks the highest
non-prerelease version of each bundled module, builds the dependency graph,
topologically sorts it (Kahn), and emits dependency-tree.md (waves = levels;
modules within a wave can be processed in parallel). Also reports the maximum
platform version required and validates there are no cycles.

The registry only knows the module.manifest dependencies. A module can also reference another module's NuGet package
in a csproj without declaring it in the manifest (Stable 16: UCP used XOrder.Data), which would put both in the same
wave and ship the dependent against the previous release. So the graph also gets an edge for every csproj reference to
an in-bundle module's package (read from origin/<sourceBranch> of the local clones), and those undeclared dependencies
are listed: the module's manifest should declare them.

Usage: python compute_waves.py
"""
import collections
import json
from packaging import version

import bump_module_deps
import config

BUNDLE = config.CUR_BUNDLE
REGISTRY = config.REGISTRY
OUT = config.out("dependency-tree.md")


def main():
    bundle = json.load(open(BUNDLE, encoding="utf-8"))
    gh = [s for s in bundle["Sources"] if s["Name"] == "GithubReleases"][0]
    wanted = {m["Id"]: m["Version"] for m in gh["Modules"]}
    data = json.load(open(REGISTRY, encoding="utf-8"))
    byid = {m["Id"]: m for m in data}

    chosen, deps, platforms = {}, {}, {}
    for mid in wanted:
        m = byid[mid]
        stables = [v for v in m["Versions"] if not v.get("VersionTag")]
        best = max(stables, key=lambda v: version.parse(v["Version"]))
        chosen[mid] = best["Version"]
        platforms[mid] = best.get("PlatformVersion")
        deps[mid] = [(d["Id"], d["Version"], d.get("Optional", False))
                     for d in (best.get("Dependencies") or [])]

    inb = set(wanted)

    # csproj-only module references (not declared in module.manifest)
    module_to_repo, package_to_module = bump_module_deps.module_index()
    undeclared = collections.defaultdict(set)
    for mid in inb:
        repo = module_to_repo.get(mid)
        if not repo:
            continue
        try:
            files = bump_module_deps.repo_files(repo, f"origin/{config.SOURCE_BRANCH}")
        except Exception:  # noqa: BLE001 - no such ref locally: fall back to the working tree
            files = bump_module_deps.repo_files(repo, None)
        declared = {d for d, _, _ in deps[mid]}
        for path, data in files:
            if not path.endswith(".csproj"):
                continue
            for match in bump_module_deps.PKG_REF.finditer(data):
                target = package_to_module.get(match.group(2).decode())
                if target and target != mid and target in inb and target not in declared:
                    undeclared[mid].add(target)
        for target in undeclared.get(mid, ()):
            deps[mid].append((target, "", False))
    undeclared = {mid: targets for mid, targets in undeclared.items() if targets}

    indeg = {m: 0 for m in inb}
    adj = collections.defaultdict(list)
    for mid in inb:
        for did, _, _ in deps[mid]:
            if did in inb:
                adj[did].append(mid)
                indeg[mid] += 1

    # Kahn topo-sort with levels
    level = {m: 0 for m in inb if indeg[m] == 0}
    q = sorted([m for m in inb if indeg[m] == 0])
    order = []
    indeg2 = dict(indeg)
    while q:
        n = q.pop(0)
        order.append(n)
        for nb in sorted(adj[n]):
            indeg2[nb] -= 1
            level[nb] = max(level.get(nb, 0), level[n] + 1)
            if indeg2[nb] == 0:
                q.append(nb)
                q.sort()
    cycles = [m for m in inb if indeg2[m] > 0]

    maxpf = max(platforms.values(), key=lambda p: version.parse(p))
    bylevel = collections.defaultdict(list)
    for m in order:
        bylevel[level[m]].append(m)

    out = []
    out.append(f"# Stable {config.VERSION} — Module update dependency tree (waves)\n")
    out.append("> Generated by `src/compute_waves.py` from `modules_v3.json` (highest "
               "non-prerelease version per bundled module). Read-only.\n")
    out.append("Waves are **sequential**; modules **within** a wave have no inter-dependency and "
               "can be prepared in parallel. Each wave builds against the modules the earlier waves "
               "released (from nuget.org, so wait for the previous wave's packages).\n")
    out.append(f"- Modules in bundle: **{len(wanted)}**")
    out.append(f"- Cycles detected: **{len(cycles)}** {cycles if cycles else '(none — DAG ok)'}")
    out.append(f"- Highest platform version required by any module: **{maxpf}** "
               f"→ Stable {config.VERSION} platform target **{config.PLATFORM_VERSION}** satisfies it.")
    out.append(f"- csproj-only module references (ordered here, missing from module.manifest): "
               f"**{sum(len(v) for v in undeclared.values())}**\n")
    if undeclared:
        out.append("## Undeclared module dependencies\n")
        out.append("These modules reference another module's package in a csproj but not in `module.manifest`. "
                   "The waves account for them (marked `*` below); the manifest should declare them.\n")
        for mid in sorted(undeclared):
            out.append(f"- {mid} → {', '.join(sorted(undeclared[mid]))}")
        out.append("")

    out.append("## Wave 0 — Platform\n")
    out.append(f"- `vc-platform` → **{config.PLATFORM_VERSION}** (released first; every module wave builds on it)\n")

    for lv in sorted(bylevel):
        mods = sorted(bylevel[lv])
        out.append(f"## Wave {lv + 1} ({len(mods)} module(s), parallel)\n")
        out.append("| Module | Target stable | Depends on (in-bundle) |")
        out.append("|---|---|---|")
        for m in mods:
            d = sorted({x for x, _, _ in deps[m] if x in inb})
            dstr = ", ".join(s.replace("VirtoCommerce.", "") + ("*" if s in undeclared.get(m, ()) else "")
                             for s in d) or "—"
            out.append(f"| {m} | {chosen[m]} | {dstr} |")
        out.append("")

    open(OUT, "w", encoding="utf-8").write("\n".join(out))
    print(f"Wrote {OUT}")
    print(f"Modules: {len(wanted)}  Waves: {max(bylevel)+2}  Cycles: {len(cycles)}  MaxPlatform: {maxpf}")


if __name__ == "__main__":
    main()
