"""
Compute the dependency-ordered update waves for a stable-release bundle.

Read-only. Reads a bundle package.json + modules_v3.json, picks the highest
non-prerelease version of each bundled module, builds the dependency graph,
topologically sorts it (Kahn), and emits dependency-tree.md (waves = levels;
modules within a wave can be processed in parallel). Also reports the maximum
platform version required and validates there are no cycles.

Usage: python compute_waves.py
"""
import collections
import json
from packaging import version

import config

BUNDLE = config.CUR_BUNDLE
REGISTRY = config.REGISTRY
OUT = config.out("dependency-tree.md")


def main():
    bundle = json.load(open(BUNDLE, encoding="utf-8"))
    gh = [s for s in bundle["Sources"] if s["Name"] == "GithubReleases"][0]
    wanted = {m["Id"]: m["Version"] for m in gh["Modules"]}
    data = json.load(open(REGISTRY, encoding="utf-8"))
    byid = {m["Id"]: m for m in data}

    chosen, deps, platforms = {}, {}, {}
    for mid in wanted:
        m = byid[mid]
        stables = [v for v in m["Versions"] if not v.get("VersionTag")]
        best = max(stables, key=lambda v: version.parse(v["Version"]))
        chosen[mid] = best["Version"]
        platforms[mid] = best.get("PlatformVersion")
        deps[mid] = [(d["Id"], d["Version"], d.get("Optional", False))
                     for d in (best.get("Dependencies") or [])]

    inb = set(wanted)
    indeg = {m: 0 for m in inb}
    adj = collections.defaultdict(list)
    for mid in inb:
        for did, _, _ in deps[mid]:
            if did in inb:
                adj[did].append(mid)
                indeg[mid] += 1

    # Kahn topo-sort with levels
    level = {m: 0 for m in inb if indeg[m] == 0}
    q = sorted([m for m in inb if indeg[m] == 0])
    order = []
    indeg2 = dict(indeg)
    while q:
        n = q.pop(0)
        order.append(n)
        for nb in sorted(adj[n]):
            indeg2[nb] -= 1
            level[nb] = max(level.get(nb, 0), level[n] + 1)
            if indeg2[nb] == 0:
                q.append(nb)
                q.sort()
    cycles = [m for m in inb if indeg2[m] > 0]

    maxpf = max(platforms.values(), key=lambda p: version.parse(p))
    bylevel = collections.defaultdict(list)
    for m in order:
        bylevel[level[m]].append(m)

    out = []
    out.append(f"# Stable {config.VERSION} — Module update dependency tree (waves)\n")
    out.append("> Generated by `src/compute_waves.py` from `modules_v3.json` (highest "
               "non-prerelease version per bundled module). Read-only.\n")
    out.append("Waves are **sequential**; modules **within** a wave have no inter-dependency and "
               "can be built in parallel. Each wave compiles against the freshly-built outputs of "
               "all earlier waves (via `local-nuget`).\n")
    out.append(f"- Modules in bundle: **{len(wanted)}**")
    out.append(f"- Cycles detected: **{len(cycles)}** {cycles if cycles else '(none — DAG ok)'}")
    out.append(f"- Highest platform version required by any module: **{maxpf}** "
               f"→ Stable {config.VERSION} platform target **{config.PLATFORM_VERSION}** satisfies it.\n")

    out.append("## Wave 0 — Platform\n")
    out.append(f"- `vc-platform` → **{config.PLATFORM_VERSION}** (clean obsolete, repack to local-nuget first)\n")

    for lv in sorted(bylevel):
        mods = sorted(bylevel[lv])
        out.append(f"## Wave {lv + 1} ({len(mods)} module(s), parallel)\n")
        out.append("| Module | Target stable | Depends on (in-bundle) |")
        out.append("|---|---|---|")
        for m in mods:
            d = sorted(x for x, _, _ in deps[m] if x in inb)
            dstr = ", ".join(s.replace("VirtoCommerce.", "") for s in d) or "—"
            out.append(f"| {m} | {chosen[m]} | {dstr} |")
        out.append("")

    open(OUT, "w", encoding="utf-8").write("\n".join(out))
    print(f"Wrote {OUT}")
    print(f"Modules: {len(wanted)}  Waves: {max(bylevel)+2}  Cycles: {len(cycles)}  MaxPlatform: {maxpf}")


if __name__ == "__main__":
    main()
