"""
Generate platform_package_reference.md from the REAL platform dependencies.

Read-only. Enumerates every project in VirtoCommerce.Platform.sln, parses each
.csproj PackageReference (Include + Version), dedupes, flags version conflicts,
and backfills license/homepage from the hand-written 3rd-party-components.md.

Usage: python platform_package_reference.py
"""
import glob
import os
import re

import config

ROOT = config.ROOT
PLATFORM = config.PLATFORM_DIR
SLN = os.path.join(PLATFORM, "VirtoCommerce.Platform.sln")
OUT = config.out("platform_package_reference.md")

PROJ_RE = re.compile(r"Project\(\"\{[^}]+\}\"\)\s*=\s*\"[^\"]+\",\s*\"([^\"]+\.csproj)\"")
PKG_RE = re.compile(r"<PackageReference\s+Include=\"([^\"]+)\"(?:\s+Version=\"([^\"]+)\")?", re.IGNORECASE)
PKG_VER_CHILD_RE = re.compile(r"<PackageReference\s+Include=\"([^\"]+)\"[^>]*>(.*?)</PackageReference>",
                              re.IGNORECASE | re.DOTALL)
VER_ELEM_RE = re.compile(r"<Version>([^<]+)</Version>", re.IGNORECASE)


def sln_projects():
    txt = open(SLN, encoding="utf-8-sig").read()
    projs = []
    for m in PROJ_RE.finditer(txt):
        rel = m.group(1).replace("\\", "/")
        p = os.path.normpath(os.path.join(PLATFORM, rel))
        if p.lower().endswith(".csproj") and os.path.isfile(p):
            projs.append(p)
    return projs


def parse_versions(csproj_text):
    """return list of (pkg, version) handling both attribute and child-element Version."""
    out = []
    seen_spans = []
    for m in PKG_VER_CHILD_RE.finditer(csproj_text):
        pkg = m.group(1)
        vm = VER_ELEM_RE.search(m.group(2))
        if vm:
            out.append((pkg, vm.group(1).strip()))
            seen_spans.append(m.span())
    for m in PKG_RE.finditer(csproj_text):
        pkg, ver = m.group(1), m.group(2)
        if ver is None:
            continue
        out.append((pkg, ver.strip()))
    # dedupe (pkg,ver) pairs
    return list(dict.fromkeys(out))


def load_3rd_party():
    """light backfill: package-name substring -> (license, homepage) from the md table."""
    info = {}
    p = os.path.join(PLATFORM, "3rd-party-components.md")
    if not os.path.isfile(p):
        return info
    for line in open(p, encoding="utf-8"):
        if not line.strip().startswith("|"):
            continue
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cells) >= 4:
            name = cells[0]
            info[name.lower()] = cells
    return info


def main():
    projs = sln_projects()
    # exclude test projects from the "shipped dependencies" view but keep a note
    pkgmap = {}  # pkg -> {version -> set(projectShortNames)}
    test_projs = []
    for p in projs:
        short = os.path.splitext(os.path.basename(p))[0]
        is_test = "test" in short.lower()
        if is_test:
            test_projs.append(short)
        try:
            txt = open(p, encoding="utf-8-sig").read()
        except Exception:
            continue
        for pkg, ver in parse_versions(txt):
            pkgmap.setdefault(pkg, {}).setdefault(ver, set())
            pkgmap[pkg][ver].add(short + (" (test)" if is_test else ""))

    third = load_3rd_party()
    out = []
    out.append(f"# Stable {config.VERSION} — Platform third-party package reference "
               f"(platform {config.PLATFORM_VERSION})\n")
    out.append("> Generated by `src/platform_package_reference.py` from the **real** "
               "`PackageReference`s in every project of `vc-platform/VirtoCommerce.Platform.sln`. "
               "Read-only.\n")
    out.append(f"- Projects in solution: **{len(projs)}** (including {len(test_projs)} test projects)")
    out.append(f"- Distinct NuGet packages referenced: **{len(pkgmap)}**")
    conflicts = {k: v for k, v in pkgmap.items() if len({ver for ver in v}) > 1}
    out.append(f"- Packages referenced at **more than one version (conflicts): {len(conflicts)}**\n")

    if conflicts:
        out.append("## ⚠️ Version conflicts (same package, multiple versions)\n")
        out.append("| Package | Versions | Projects |")
        out.append("|---|---|---|")
        for pkg in sorted(conflicts):
            vers = pkgmap[pkg]
            vstr = "<br>".join(f"`{ver}` — {', '.join(sorted(vers[ver]))}" for ver in sorted(vers))
            out.append(f"| {pkg} | {', '.join(sorted(vers))} | {vstr} |")
        out.append("")

    out.append("## All packages (deduped)\n")
    out.append("| Package | Version(s) | # Projects | License | Homepage |")
    out.append("|---|---|--:|---|---|")
    for pkg in sorted(pkgmap, key=str.lower):
        vers = pkgmap[pkg]
        nproj = len({p for ver in vers for p in vers[ver]})
        vstr = ", ".join(f"`{v}`" for v in sorted(vers))
        meta = third.get(pkg.lower())
        lic = home = ""
        if meta and len(meta) >= 4:
            lic = meta[2] if len(meta) > 2 else ""
            home = meta[3] if len(meta) > 3 else ""
        out.append(f"| {pkg} | {vstr} | {nproj} | {lic} | {home} |")
    out.append("")

    open(OUT, "w", encoding="utf-8").write("\n".join(out))
    print(f"Wrote {OUT}")
    print(f"Projects: {len(projs)}  Packages: {len(pkgmap)}  Conflicts: {len(conflicts)}")
    if conflicts:
        print("Conflicting packages:", ", ".join(sorted(conflicts)))


if __name__ == "__main__":
    main()
